
# mode: train
mode: train test test_channel visual visual_proto
# mode: test
# mode: visual
# # mode: visual_proto
# mode: test test_channel
# mode: test visual visual_proto
# mode: test_channel visual visual_proto 
batch_size: 128
learning_rate: 0.001
epochs: 10
beta: 0.25
window_size: 100

time_recon:
  patch_size: 30
  in_dim: 9
  n_hiddens: 64
  n_residual_hiddens: 64
  n_residual_layers: 2
  embedding_dim: 64
  n_embeddings: 16
  activation: gelu
  top_k: 2

freq_recon:
  patch_size: 30
  in_dim: 9
  n_hiddens: 32
  n_residual_hiddens: 32
  n_residual_layers: 2
  embedding_dim: 32
  n_embeddings: 16
  activation: gelu
  top_k: 2

aggregate: mean
topk: 2
alpha: 1
beta: 0.01

log_interval: 50
dataset: 249_DLR.csv

# Boolean flags in YAML use true/false
save: true
filename: dlr  # will default to timestamp if empty
visual_channel: [0]

